### PR TITLE
(MAINT) Drop Ruby 2.1.9/puppet 4.x from packaging

### PR DESCRIPTION
**Pull request by scotje**
Tests will still fail due to rspec-puppet needing a 2.8.0 release, but this should start of fix the packaging step.

### CODE REVIEW

**Comment by scotje** [comment]
Tests should pass once https://github.com/puppetlabs/pdk/pull/919 is merged.

**Comment by scotje** [comment]
Still some test failures in the version selection spec, going to look at those tomorrow.

**Review by DavidS — APPROVED** [review]
wow :fire: :+1:

**Comment by DavidS** [comment]
looking forward to getting rid of ruby 2.1 and puppet4 across all our tooling

**Comment by scotje** [comment]
Identified the (hopefully) last blocker on Windows (Bundler issues with paths containing spaces), working up updating this to patch bundler as needed.

**Comment by scotje** [comment]
Finally got a passing build: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/PDK/view/adhoc/job/platform_pdk_adhoc_pdk-int-sys-testing_adhoc/124/

**Pull request merged**
