### PR TITLE
(RE-13303) Update project definition to sign PuppetDevelopmentKit.psm1 at build time

### PR DESCRIPTION
**Pull request by underscorgan**
Blocked by https://github.com/puppetlabs/vanagon/pull/652

### CODE REVIEW

**Comment by underscorgan** [comment]
Screen Shot showing a signed and timestamped PuppetDevelopmentKit.psm1 file

**Comment by sanfrancrisko** [comment]
Will be able to test this when https://github.com/puppetlabs/vanagon/pull/652 is merged. Looks ready to go - [left a comment](https://github.com/puppetlabs/vanagon/pull/652#issuecomment-641874053) asking if someone could let us know when this is ready.

**Comment by underscorgan** [comment]
Hi @sanfrancrisko , we just released vanagon 0.15.38 which has the code changes needed for this

**Comment by DavidS** [comment]
:crossed_fingers:

**Pull request merged**
