### PR TITLE
(PDK-1375) Use Tarball method for MSI based packages

### PR DESCRIPTION
**Pull request by glennsarti**
This Pull Request merges the Improved MSI feature back into master

It consists of the following issues
(PDK-1370) Create tarballs of ruby environment for Windows
(PDK-1371) Extract tarballs during MSI Installation
(PDK-1373) Remove extracted files on MSI uninstall

### CODE REVIEW

**Comment by Iristyle** [comment]
Haven't looked at the code in detail, but I like the promise of faster installs!

Is there a way that we could make the Ruby tarballs an output of puppet runtime project and consume the component differently in downstream projects? PDK, Agent and Bolt all suffer from this same basic perf issue on Windows, and it would be nice to build things in a way that can be easily leveraged by all of the installers.

/cc @underscorgan @sarameisburger @shrug

**Comment by glennsarti** [comment]
> PDK, Agent and Bolt all suffer from this same basic perf issue on Windows, 

One thing we could immediately do is implement @rodjek Gem "cruft remover" - https://github.com/puppetlabs/pdk-vanagon/commit/3b3eb60eb40459e27d4309f71f6623c99b070eef

It removes things like specs, tests etc. from vendored gems as they're not required at runtime.

**Comment by glennsarti** [comment]
Pipelines are currently red.  I'll get that fixed up and then merge this.

**Comment by glennsarti** [comment]
Pending https://github.com/puppetlabs/pdk/pull/709

**Comment by glennsarti** [comment]
Pipelines are now green.  Merging.

**Pull request merged**
