### PR TITLE
(PDK-493) Use a runtime

### PR DESCRIPTION
**Pull request by underscorgan**

### CODE REVIEW

**Comment by underscorgan** [comment]
relates to: https://github.com/puppetlabs/puppet-runtime/pull/1

**Comment by underscorgan** [comment]
@DavidS Yeah, I'll probably want to get the runtime updated with curl and get that PR merged in, I'll try to get that in today!

**Comment by underscorgan** [comment]
Pending https://github.com/puppetlabs/puppet-runtime/pull/2 and a rebuild of the runtime to not lose the curl update

**Comment by underscorgan** [comment]
That runtime PR was merged, I've updated the runtime component to the latest tag (building now at http://jenkins-release.delivery.puppetlabs.net/job/vanagon_generic_job/1292/) so this should be good to go whenever you're ready/when that job finishes. Probably want to try a test build just to make sure everything looks 👍 , but wanted to get the changes staged since the runtime build won't be done before I sign off for the night.

**Comment by underscorgan** [comment]
I was able to successfully build this (http://jenkins-release.delivery.puppetlabs.net/job/vanagon_generic_job/1298/) with one caveat: This build lead me to find a bug in vanagon which has since been fixed (http://jenkins-release.delivery.puppetlabs.net/job/vanagon_generic_job/1298/) but would require building off of master of vanagon until our next regularly scheduled release of next tuesday

**Comment by DavidS** [comment]
Since we're gearing up for 1.3 release in the next few days, @bmjen and I decided it would be better to avoid merging that right now, to avoid last minute risks. We'll merge that immediately afterwards to get maximum soak time until the next release.

I can't wait :-D

**Comment by underscorgan** [comment]
ok, sounds great! Looks like there's another conflict, I'll get that updated

**Comment by DavidS** [comment]
Don't worry too much about conflicts just now. We need to pick this up ourselves anyways once the PDK is in a place to receive this change.

**Comment by underscorgan** [comment]
happy-dance

**Pull request merged**
